/* Exported the input default values for better readability */
export const inputTypes = {
  email: "",
  number: "",
  password: "",
  tel: "",
  text: "",
  url: "",
  textarea: "",
  date: "",
  datetimeLocal: "",
  month: "",
  time: "",
  week: "",
  radio: false,
  range: 0,
  checkbox: false,
  color: "#345623",
  file: "",
};
